/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DataElement;
import org.openapitools.client.model.Leg;
import org.openapitools.client.model.PeriodOfOperation;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FlightAggregate
 */
class FlightAggregateTest {
    private final FlightAggregate model = new FlightAggregate();

    /**
     * Model tests for FlightAggregate
     */
    @Test
    void testFlightAggregate() {
        // TODO: test FlightAggregate
    }

    /**
     * Test the property 'airline'
     */
    @Test
    void airlineTest() {
        // TODO: test airline
    }

    /**
     * Test the property 'flightNumber'
     */
    @Test
    void flightNumberTest() {
        // TODO: test flightNumber
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'periodOfOperationUTC'
     */
    @Test
    void periodOfOperationUTCTest() {
        // TODO: test periodOfOperationUTC
    }

    /**
     * Test the property 'periodOfOperationLT'
     */
    @Test
    void periodOfOperationLTTest() {
        // TODO: test periodOfOperationLT
    }

    /**
     * Test the property 'legs'
     */
    @Test
    void legsTest() {
        // TODO: test legs
    }

    /**
     * Test the property 'dataElements'
     */
    @Test
    void dataElementsTest() {
        // TODO: test dataElements
    }

}
