/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Leg
 */
class LegTest {
    private final Leg model = new Leg();

    /**
     * Model tests for Leg
     */
    @Test
    void testLeg() {
        // TODO: test Leg
    }

    /**
     * Test the property 'sequenceNumber'
     */
    @Test
    void sequenceNumberTest() {
        // TODO: test sequenceNumber
    }

    /**
     * Test the property 'origin'
     */
    @Test
    void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'destination'
     */
    @Test
    void destinationTest() {
        // TODO: test destination
    }

    /**
     * Test the property 'serviceType'
     */
    @Test
    void serviceTypeTest() {
        // TODO: test serviceType
    }

    /**
     * Test the property 'aircraftOwner'
     */
    @Test
    void aircraftOwnerTest() {
        // TODO: test aircraftOwner
    }

    /**
     * Test the property 'aircraftType'
     */
    @Test
    void aircraftTypeTest() {
        // TODO: test aircraftType
    }

    /**
     * Test the property 'aircraftConfigurationVersion'
     */
    @Test
    void aircraftConfigurationVersionTest() {
        // TODO: test aircraftConfigurationVersion
    }

    /**
     * Test the property 'registration'
     */
    @Test
    void registrationTest() {
        // TODO: test registration
    }

    /**
     * Test the property 'op'
     */
    @Test
    void opTest() {
        // TODO: test op
    }

    /**
     * Test the property 'aircraftDepartureTimeUTC'
     */
    @Test
    void aircraftDepartureTimeUTCTest() {
        // TODO: test aircraftDepartureTimeUTC
    }

    /**
     * Test the property 'aircraftDepartureTimeDateDiffUTC'
     */
    @Test
    void aircraftDepartureTimeDateDiffUTCTest() {
        // TODO: test aircraftDepartureTimeDateDiffUTC
    }

    /**
     * Test the property 'aircraftDepartureTimeLT'
     */
    @Test
    void aircraftDepartureTimeLTTest() {
        // TODO: test aircraftDepartureTimeLT
    }

    /**
     * Test the property 'aircraftDepartureTimeDateDiffLT'
     */
    @Test
    void aircraftDepartureTimeDateDiffLTTest() {
        // TODO: test aircraftDepartureTimeDateDiffLT
    }

    /**
     * Test the property 'aircraftDepartureTimeVariation'
     */
    @Test
    void aircraftDepartureTimeVariationTest() {
        // TODO: test aircraftDepartureTimeVariation
    }

    /**
     * Test the property 'aircraftArrivalTimeUTC'
     */
    @Test
    void aircraftArrivalTimeUTCTest() {
        // TODO: test aircraftArrivalTimeUTC
    }

    /**
     * Test the property 'aircraftArrivalTimeDateDiffUTC'
     */
    @Test
    void aircraftArrivalTimeDateDiffUTCTest() {
        // TODO: test aircraftArrivalTimeDateDiffUTC
    }

    /**
     * Test the property 'aircraftArrivalTimeLT'
     */
    @Test
    void aircraftArrivalTimeLTTest() {
        // TODO: test aircraftArrivalTimeLT
    }

    /**
     * Test the property 'aircraftArrivalTimeDateDiffLT'
     */
    @Test
    void aircraftArrivalTimeDateDiffLTTest() {
        // TODO: test aircraftArrivalTimeDateDiffLT
    }

    /**
     * Test the property 'aircraftArrivalTimeVariation'
     */
    @Test
    void aircraftArrivalTimeVariationTest() {
        // TODO: test aircraftArrivalTimeVariation
    }

}
