/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A data element is an additional flight attribute as defined in SSIM, Chapter 2 dealing with a variety of characteristics, e.g.: * Traffic Restriction: 8 * Codeshare - Duplicate leg cross-reference: 10 * Codeshare - Operational leg cross-reference: 50 * Departure Terminal: 99 * Arrival Terminal: 98 * Passenger Reservation Booking Designator (PRBD): 106 * Meal service note: 109 * Inflight Service: 503 * Electronic Ticket Indicator: 505 * etc. 
 */
@JsonPropertyOrder({
  DataElement.JSON_PROPERTY_START_LEG_SEQUENCE_NUMBER,
  DataElement.JSON_PROPERTY_END_LEG_SEQUENCE_NUMBER,
  DataElement.JSON_PROPERTY_ID,
  DataElement.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class DataElement {
  public static final String JSON_PROPERTY_START_LEG_SEQUENCE_NUMBER = "startLegSequenceNumber";
  @javax.annotation.Nonnull
  private Integer startLegSequenceNumber;

  public static final String JSON_PROPERTY_END_LEG_SEQUENCE_NUMBER = "endLegSequenceNumber";
  @javax.annotation.Nonnull
  private Integer endLegSequenceNumber;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private String value;

  public DataElement() {
  }

  public DataElement startLegSequenceNumber(@javax.annotation.Nonnull Integer startLegSequenceNumber) {
    
    this.startLegSequenceNumber = startLegSequenceNumber;
    return this;
  }

  /**
   * The sequence number of the leg where data element boardpoint belongs to
   * minimum: 1
   * @return startLegSequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_START_LEG_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getStartLegSequenceNumber() {
    return startLegSequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_START_LEG_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartLegSequenceNumber(@javax.annotation.Nonnull Integer startLegSequenceNumber) {
    this.startLegSequenceNumber = startLegSequenceNumber;
  }

  public DataElement endLegSequenceNumber(@javax.annotation.Nonnull Integer endLegSequenceNumber) {
    
    this.endLegSequenceNumber = endLegSequenceNumber;
    return this;
  }

  /**
   * The sequence number of the leg where data element offpoint belongs to
   * minimum: 1
   * @return endLegSequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_END_LEG_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEndLegSequenceNumber() {
    return endLegSequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_END_LEG_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndLegSequenceNumber(@javax.annotation.Nonnull Integer endLegSequenceNumber) {
    this.endLegSequenceNumber = endLegSequenceNumber;
  }

  public DataElement id(@javax.annotation.Nonnull Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * The data element identifier - see SSIM, Chapter 2 for additional information
   * minimum: 1
   * maximum: 999
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }

  public DataElement value(@javax.annotation.Nullable String value) {
    
    this.value = value;
    return this;
  }

  /**
   * The data element value itself
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataElement dataElement = (DataElement) o;
    return Objects.equals(this.startLegSequenceNumber, dataElement.startLegSequenceNumber) &&
        Objects.equals(this.endLegSequenceNumber, dataElement.endLegSequenceNumber) &&
        Objects.equals(this.id, dataElement.id) &&
        Objects.equals(this.value, dataElement.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startLegSequenceNumber, endLegSequenceNumber, id, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataElement {\n");
    sb.append("    startLegSequenceNumber: ").append(toIndentedString(startLegSequenceNumber)).append("\n");
    sb.append("    endLegSequenceNumber: ").append(toIndentedString(endLegSequenceNumber)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

