/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Message;
import org.openapitools.client.model.TechnicalMessage;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ErrorResponse
 */
@JsonPropertyOrder({
  ErrorResponse.JSON_PROPERTY_HTTP_STATUS,
  ErrorResponse.JSON_PROPERTY_MESSAGES,
  ErrorResponse.JSON_PROPERTY_TECHNICAL_MESSAGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class ErrorResponse {
  public static final String JSON_PROPERTY_HTTP_STATUS = "httpStatus";
  @javax.annotation.Nullable
  private Integer httpStatus;

  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @javax.annotation.Nullable
  private List<Message> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_TECHNICAL_MESSAGES = "technicalMessages";
  @javax.annotation.Nullable
  private List<TechnicalMessage> technicalMessages = new ArrayList<>();

  public ErrorResponse() {
  }

  public ErrorResponse httpStatus(@javax.annotation.Nullable Integer httpStatus) {
    
    this.httpStatus = httpStatus;
    return this;
  }

  /**
   * Get httpStatus
   * @return httpStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HTTP_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHttpStatus() {
    return httpStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_HTTP_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpStatus(@javax.annotation.Nullable Integer httpStatus) {
    this.httpStatus = httpStatus;
  }

  public ErrorResponse messages(@javax.annotation.Nullable List<Message> messages) {
    
    this.messages = messages;
    return this;
  }

  public ErrorResponse addMessagesItem(Message messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Message> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessages(@javax.annotation.Nullable List<Message> messages) {
    this.messages = messages;
  }

  public ErrorResponse technicalMessages(@javax.annotation.Nullable List<TechnicalMessage> technicalMessages) {
    
    this.technicalMessages = technicalMessages;
    return this;
  }

  public ErrorResponse addTechnicalMessagesItem(TechnicalMessage technicalMessagesItem) {
    if (this.technicalMessages == null) {
      this.technicalMessages = new ArrayList<>();
    }
    this.technicalMessages.add(technicalMessagesItem);
    return this;
  }

  /**
   * Get technicalMessages
   * @return technicalMessages
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TECHNICAL_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TechnicalMessage> getTechnicalMessages() {
    return technicalMessages;
  }


  @JsonProperty(value = JSON_PROPERTY_TECHNICAL_MESSAGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTechnicalMessages(@javax.annotation.Nullable List<TechnicalMessage> technicalMessages) {
    this.technicalMessages = technicalMessages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse errorResponse = (ErrorResponse) o;
    return Objects.equals(this.httpStatus, errorResponse.httpStatus) &&
        Objects.equals(this.messages, errorResponse.messages) &&
        Objects.equals(this.technicalMessages, errorResponse.technicalMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpStatus, messages, technicalMessages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponse {\n");
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    technicalMessages: ").append(toIndentedString(technicalMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

