/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DataElement;
import org.openapitools.client.model.Leg;
import org.openapitools.client.model.PeriodOfOperation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A FlightAggregate is a date-wise aggregation of otherwise single-dated flights. I.e. flights with identical attributes are aggregated into periods of operation.
 */
@JsonPropertyOrder({
  FlightAggregate.JSON_PROPERTY_AIRLINE,
  FlightAggregate.JSON_PROPERTY_FLIGHT_NUMBER,
  FlightAggregate.JSON_PROPERTY_SUFFIX,
  FlightAggregate.JSON_PROPERTY_PERIOD_OF_OPERATION_U_T_C,
  FlightAggregate.JSON_PROPERTY_PERIOD_OF_OPERATION_L_T,
  FlightAggregate.JSON_PROPERTY_LEGS,
  FlightAggregate.JSON_PROPERTY_DATA_ELEMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class FlightAggregate {
  public static final String JSON_PROPERTY_AIRLINE = "airline";
  @javax.annotation.Nullable
  private String airline;

  public static final String JSON_PROPERTY_FLIGHT_NUMBER = "flightNumber";
  @javax.annotation.Nullable
  private Integer flightNumber;

  public static final String JSON_PROPERTY_SUFFIX = "suffix";
  @javax.annotation.Nullable
  private String suffix;

  public static final String JSON_PROPERTY_PERIOD_OF_OPERATION_U_T_C = "periodOfOperationUTC";
  @javax.annotation.Nullable
  private PeriodOfOperation periodOfOperationUTC;

  public static final String JSON_PROPERTY_PERIOD_OF_OPERATION_L_T = "periodOfOperationLT";
  @javax.annotation.Nullable
  private PeriodOfOperation periodOfOperationLT;

  public static final String JSON_PROPERTY_LEGS = "legs";
  @javax.annotation.Nullable
  private List<Leg> legs = new ArrayList<>();

  public static final String JSON_PROPERTY_DATA_ELEMENTS = "dataElements";
  @javax.annotation.Nullable
  private List<DataElement> dataElements = new ArrayList<>();

  public FlightAggregate() {
  }

  public FlightAggregate airline(@javax.annotation.Nullable String airline) {
    
    this.airline = airline;
    return this;
  }

  /**
   * The airline code of the flight
   * @return airline
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRLINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAirline() {
    return airline;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRLINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAirline(@javax.annotation.Nullable String airline) {
    this.airline = airline;
  }

  public FlightAggregate flightNumber(@javax.annotation.Nullable Integer flightNumber) {
    
    this.flightNumber = flightNumber;
    return this;
  }

  /**
   * The flight number
   * minimum: 1
   * maximum: 9999
   * @return flightNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLIGHT_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFlightNumber() {
    return flightNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_FLIGHT_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlightNumber(@javax.annotation.Nullable Integer flightNumber) {
    this.flightNumber = flightNumber;
  }

  public FlightAggregate suffix(@javax.annotation.Nullable String suffix) {
    
    this.suffix = suffix;
    return this;
  }

  /**
   * Operational suffix. One character or empty string.
   * @return suffix
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUFFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSuffix() {
    return suffix;
  }


  @JsonProperty(value = JSON_PROPERTY_SUFFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuffix(@javax.annotation.Nullable String suffix) {
    this.suffix = suffix;
  }

  public FlightAggregate periodOfOperationUTC(@javax.annotation.Nullable PeriodOfOperation periodOfOperationUTC) {
    
    this.periodOfOperationUTC = periodOfOperationUTC;
    return this;
  }

  /**
   * Get periodOfOperationUTC
   * @return periodOfOperationUTC
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERIOD_OF_OPERATION_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PeriodOfOperation getPeriodOfOperationUTC() {
    return periodOfOperationUTC;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_OF_OPERATION_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodOfOperationUTC(@javax.annotation.Nullable PeriodOfOperation periodOfOperationUTC) {
    this.periodOfOperationUTC = periodOfOperationUTC;
  }

  public FlightAggregate periodOfOperationLT(@javax.annotation.Nullable PeriodOfOperation periodOfOperationLT) {
    
    this.periodOfOperationLT = periodOfOperationLT;
    return this;
  }

  /**
   * Get periodOfOperationLT
   * @return periodOfOperationLT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERIOD_OF_OPERATION_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PeriodOfOperation getPeriodOfOperationLT() {
    return periodOfOperationLT;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD_OF_OPERATION_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodOfOperationLT(@javax.annotation.Nullable PeriodOfOperation periodOfOperationLT) {
    this.periodOfOperationLT = periodOfOperationLT;
  }

  public FlightAggregate legs(@javax.annotation.Nullable List<Leg> legs) {
    
    this.legs = legs;
    return this;
  }

  public FlightAggregate addLegsItem(Leg legsItem) {
    if (this.legs == null) {
      this.legs = new ArrayList<>();
    }
    this.legs.add(legsItem);
    return this;
  }

  /**
   * The legs
   * @return legs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Leg> getLegs() {
    return legs;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegs(@javax.annotation.Nullable List<Leg> legs) {
    this.legs = legs;
  }

  public FlightAggregate dataElements(@javax.annotation.Nullable List<DataElement> dataElements) {
    
    this.dataElements = dataElements;
    return this;
  }

  public FlightAggregate addDataElementsItem(DataElement dataElementsItem) {
    if (this.dataElements == null) {
      this.dataElements = new ArrayList<>();
    }
    this.dataElements.add(dataElementsItem);
    return this;
  }

  /**
   * The data elements
   * @return dataElements
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_ELEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DataElement> getDataElements() {
    return dataElements;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_ELEMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataElements(@javax.annotation.Nullable List<DataElement> dataElements) {
    this.dataElements = dataElements;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightAggregate flightAggregate = (FlightAggregate) o;
    return Objects.equals(this.airline, flightAggregate.airline) &&
        Objects.equals(this.flightNumber, flightAggregate.flightNumber) &&
        Objects.equals(this.suffix, flightAggregate.suffix) &&
        Objects.equals(this.periodOfOperationUTC, flightAggregate.periodOfOperationUTC) &&
        Objects.equals(this.periodOfOperationLT, flightAggregate.periodOfOperationLT) &&
        Objects.equals(this.legs, flightAggregate.legs) &&
        Objects.equals(this.dataElements, flightAggregate.dataElements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airline, flightNumber, suffix, periodOfOperationUTC, periodOfOperationLT, legs, dataElements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightAggregate {\n");
    sb.append("    airline: ").append(toIndentedString(airline)).append("\n");
    sb.append("    flightNumber: ").append(toIndentedString(flightNumber)).append("\n");
    sb.append("    suffix: ").append(toIndentedString(suffix)).append("\n");
    sb.append("    periodOfOperationUTC: ").append(toIndentedString(periodOfOperationUTC)).append("\n");
    sb.append("    periodOfOperationLT: ").append(toIndentedString(periodOfOperationLT)).append("\n");
    sb.append("    legs: ").append(toIndentedString(legs)).append("\n");
    sb.append("    dataElements: ").append(toIndentedString(dataElements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

