/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A flight&#39;s leg is a smaller part of an overall journey which involves landing at an intermediate airport
 */
@JsonPropertyOrder({
  Leg.JSON_PROPERTY_SEQUENCE_NUMBER,
  Leg.JSON_PROPERTY_ORIGIN,
  Leg.JSON_PROPERTY_DESTINATION,
  Leg.JSON_PROPERTY_SERVICE_TYPE,
  Leg.JSON_PROPERTY_AIRCRAFT_OWNER,
  Leg.JSON_PROPERTY_AIRCRAFT_TYPE,
  Leg.JSON_PROPERTY_AIRCRAFT_CONFIGURATION_VERSION,
  Leg.JSON_PROPERTY_REGISTRATION,
  Leg.JSON_PROPERTY_OP,
  Leg.JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_U_T_C,
  Leg.JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_U_T_C,
  Leg.JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_L_T,
  Leg.JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_L_T,
  Leg.JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_VARIATION,
  Leg.JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_U_T_C,
  Leg.JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_U_T_C,
  Leg.JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_L_T,
  Leg.JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_L_T,
  Leg.JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_VARIATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class Leg {
  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequenceNumber";
  @javax.annotation.Nonnull
  private Integer sequenceNumber;

  public static final String JSON_PROPERTY_ORIGIN = "origin";
  @javax.annotation.Nonnull
  private String origin;

  public static final String JSON_PROPERTY_DESTINATION = "destination";
  @javax.annotation.Nonnull
  private String destination;

  public static final String JSON_PROPERTY_SERVICE_TYPE = "serviceType";
  @javax.annotation.Nonnull
  private String serviceType;

  public static final String JSON_PROPERTY_AIRCRAFT_OWNER = "aircraftOwner";
  @javax.annotation.Nullable
  private String aircraftOwner;

  public static final String JSON_PROPERTY_AIRCRAFT_TYPE = "aircraftType";
  @javax.annotation.Nonnull
  private String aircraftType;

  public static final String JSON_PROPERTY_AIRCRAFT_CONFIGURATION_VERSION = "aircraftConfigurationVersion";
  @javax.annotation.Nullable
  private String aircraftConfigurationVersion;

  public static final String JSON_PROPERTY_REGISTRATION = "registration";
  @javax.annotation.Nullable
  private String registration;

  public static final String JSON_PROPERTY_OP = "op";
  @javax.annotation.Nullable
  private Boolean op;

  public static final String JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_U_T_C = "aircraftDepartureTimeUTC";
  @javax.annotation.Nullable
  private Integer aircraftDepartureTimeUTC;

  public static final String JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_U_T_C = "aircraftDepartureTimeDateDiffUTC";
  @javax.annotation.Nullable
  private Integer aircraftDepartureTimeDateDiffUTC;

  public static final String JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_L_T = "aircraftDepartureTimeLT";
  @javax.annotation.Nullable
  private Integer aircraftDepartureTimeLT;

  public static final String JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_L_T = "aircraftDepartureTimeDateDiffLT";
  @javax.annotation.Nullable
  private Integer aircraftDepartureTimeDateDiffLT;

  public static final String JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_VARIATION = "aircraftDepartureTimeVariation";
  @javax.annotation.Nullable
  private Integer aircraftDepartureTimeVariation;

  public static final String JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_U_T_C = "aircraftArrivalTimeUTC";
  @javax.annotation.Nullable
  private Integer aircraftArrivalTimeUTC;

  public static final String JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_U_T_C = "aircraftArrivalTimeDateDiffUTC";
  @javax.annotation.Nullable
  private Integer aircraftArrivalTimeDateDiffUTC;

  public static final String JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_L_T = "aircraftArrivalTimeLT";
  @javax.annotation.Nullable
  private Integer aircraftArrivalTimeLT;

  public static final String JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_L_T = "aircraftArrivalTimeDateDiffLT";
  @javax.annotation.Nullable
  private Integer aircraftArrivalTimeDateDiffLT;

  public static final String JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_VARIATION = "aircraftArrivalTimeVariation";
  @javax.annotation.Nullable
  private Integer aircraftArrivalTimeVariation;

  public Leg() {
  }

  public Leg sequenceNumber(@javax.annotation.Nonnull Integer sequenceNumber) {
    
    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * The sequence number of this leg in the associated itinerary
   * minimum: 1
   * @return sequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSequenceNumber() {
    return sequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequenceNumber(@javax.annotation.Nonnull Integer sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  public Leg origin(@javax.annotation.Nonnull String origin) {
    
    this.origin = origin;
    return this;
  }

  /**
   * The departure airport code
   * @return origin
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ORIGIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrigin() {
    return origin;
  }


  @JsonProperty(value = JSON_PROPERTY_ORIGIN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrigin(@javax.annotation.Nonnull String origin) {
    this.origin = origin;
  }

  public Leg destination(@javax.annotation.Nonnull String destination) {
    
    this.destination = destination;
    return this;
  }

  /**
   * The arrival airport code
   * @return destination
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDestination() {
    return destination;
  }


  @JsonProperty(value = JSON_PROPERTY_DESTINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDestination(@javax.annotation.Nonnull String destination) {
    this.destination = destination;
  }

  public Leg serviceType(@javax.annotation.Nonnull String serviceType) {
    
    this.serviceType = serviceType;
    return this;
  }

  /**
   * The service type of the leg. An uppercase letter.
   * @return serviceType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SERVICE_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getServiceType() {
    return serviceType;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServiceType(@javax.annotation.Nonnull String serviceType) {
    this.serviceType = serviceType;
  }

  public Leg aircraftOwner(@javax.annotation.Nullable String aircraftOwner) {
    
    this.aircraftOwner = aircraftOwner;
    return this;
  }

  /**
   * The aircraft owner or administrative carrier (an airline code) of the leg
   * @return aircraftOwner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAircraftOwner() {
    return aircraftOwner;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftOwner(@javax.annotation.Nullable String aircraftOwner) {
    this.aircraftOwner = aircraftOwner;
  }

  public Leg aircraftType(@javax.annotation.Nonnull String aircraftType) {
    
    this.aircraftType = aircraftType;
    return this;
  }

  /**
   * The fleet type identifier 3 characters, can contain letters and numbers.
   * @return aircraftType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAircraftType() {
    return aircraftType;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAircraftType(@javax.annotation.Nonnull String aircraftType) {
    this.aircraftType = aircraftType;
  }

  public Leg aircraftConfigurationVersion(@javax.annotation.Nullable String aircraftConfigurationVersion) {
    
    this.aircraftConfigurationVersion = aircraftConfigurationVersion;
    return this;
  }

  /**
   * The Aircraft Configuration/Version.
   * @return aircraftConfigurationVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_CONFIGURATION_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAircraftConfigurationVersion() {
    return aircraftConfigurationVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_CONFIGURATION_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftConfigurationVersion(@javax.annotation.Nullable String aircraftConfigurationVersion) {
    this.aircraftConfigurationVersion = aircraftConfigurationVersion;
  }

  public Leg registration(@javax.annotation.Nullable String registration) {
    
    this.registration = registration;
    return this;
  }

  /**
   * Aircraft Registration Information
   * @return registration
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REGISTRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegistration() {
    return registration;
  }


  @JsonProperty(value = JSON_PROPERTY_REGISTRATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistration(@javax.annotation.Nullable String registration) {
    this.registration = registration;
  }

  public Leg op(@javax.annotation.Nullable Boolean op) {
    
    this.op = op;
    return this;
  }

  /**
   * Signals whether this is an operating or a marketing leg
   * @return op
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOp() {
    return op;
  }


  @JsonProperty(value = JSON_PROPERTY_OP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOp(@javax.annotation.Nullable Boolean op) {
    this.op = op;
  }

  public Leg aircraftDepartureTimeUTC(@javax.annotation.Nullable Integer aircraftDepartureTimeUTC) {
    
    this.aircraftDepartureTimeUTC = aircraftDepartureTimeUTC;
    return this;
  }

  /**
   * The UTC Aircraft Scheduled Time of Departure for this leg in minutes
   * minimum: 0
   * maximum: 1439
   * @return aircraftDepartureTimeUTC
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftDepartureTimeUTC() {
    return aircraftDepartureTimeUTC;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftDepartureTimeUTC(@javax.annotation.Nullable Integer aircraftDepartureTimeUTC) {
    this.aircraftDepartureTimeUTC = aircraftDepartureTimeUTC;
  }

  public Leg aircraftDepartureTimeDateDiffUTC(@javax.annotation.Nullable Integer aircraftDepartureTimeDateDiffUTC) {
    
    this.aircraftDepartureTimeDateDiffUTC = aircraftDepartureTimeDateDiffUTC;
    return this;
  }

  /**
   * The date difference between the flight UTC date and the aircraft departure time of this leg in days.
   * minimum: -1
   * maximum: 10
   * @return aircraftDepartureTimeDateDiffUTC
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftDepartureTimeDateDiffUTC() {
    return aircraftDepartureTimeDateDiffUTC;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftDepartureTimeDateDiffUTC(@javax.annotation.Nullable Integer aircraftDepartureTimeDateDiffUTC) {
    this.aircraftDepartureTimeDateDiffUTC = aircraftDepartureTimeDateDiffUTC;
  }

  public Leg aircraftDepartureTimeLT(@javax.annotation.Nullable Integer aircraftDepartureTimeLT) {
    
    this.aircraftDepartureTimeLT = aircraftDepartureTimeLT;
    return this;
  }

  /**
   * The LT Aircraft Scheduled Time of Departure for this leg in minutes
   * minimum: 0
   * maximum: 1439
   * @return aircraftDepartureTimeLT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftDepartureTimeLT() {
    return aircraftDepartureTimeLT;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftDepartureTimeLT(@javax.annotation.Nullable Integer aircraftDepartureTimeLT) {
    this.aircraftDepartureTimeLT = aircraftDepartureTimeLT;
  }

  public Leg aircraftDepartureTimeDateDiffLT(@javax.annotation.Nullable Integer aircraftDepartureTimeDateDiffLT) {
    
    this.aircraftDepartureTimeDateDiffLT = aircraftDepartureTimeDateDiffLT;
    return this;
  }

  /**
   * The date difference between the flight LT date and the aircraft departure time of this leg in days.
   * minimum: -1
   * maximum: 10
   * @return aircraftDepartureTimeDateDiffLT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftDepartureTimeDateDiffLT() {
    return aircraftDepartureTimeDateDiffLT;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_DATE_DIFF_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftDepartureTimeDateDiffLT(@javax.annotation.Nullable Integer aircraftDepartureTimeDateDiffLT) {
    this.aircraftDepartureTimeDateDiffLT = aircraftDepartureTimeDateDiffLT;
  }

  public Leg aircraftDepartureTimeVariation(@javax.annotation.Nullable Integer aircraftDepartureTimeVariation) {
    
    this.aircraftDepartureTimeVariation = aircraftDepartureTimeVariation;
    return this;
  }

  /**
   * The departure time difference between the LT and UTC time in minutes.
   * @return aircraftDepartureTimeVariation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_VARIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftDepartureTimeVariation() {
    return aircraftDepartureTimeVariation;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_DEPARTURE_TIME_VARIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftDepartureTimeVariation(@javax.annotation.Nullable Integer aircraftDepartureTimeVariation) {
    this.aircraftDepartureTimeVariation = aircraftDepartureTimeVariation;
  }

  public Leg aircraftArrivalTimeUTC(@javax.annotation.Nullable Integer aircraftArrivalTimeUTC) {
    
    this.aircraftArrivalTimeUTC = aircraftArrivalTimeUTC;
    return this;
  }

  /**
   * The UTC Aircraft Scheduled Time of Arrival for this leg in minutes
   * minimum: 1
   * maximum: 1440
   * @return aircraftArrivalTimeUTC
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftArrivalTimeUTC() {
    return aircraftArrivalTimeUTC;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftArrivalTimeUTC(@javax.annotation.Nullable Integer aircraftArrivalTimeUTC) {
    this.aircraftArrivalTimeUTC = aircraftArrivalTimeUTC;
  }

  public Leg aircraftArrivalTimeDateDiffUTC(@javax.annotation.Nullable Integer aircraftArrivalTimeDateDiffUTC) {
    
    this.aircraftArrivalTimeDateDiffUTC = aircraftArrivalTimeDateDiffUTC;
    return this;
  }

  /**
   * The date difference between the flight UTC date and the aircraftarrival time of this leg in days.
   * minimum: -1
   * maximum: 10
   * @return aircraftArrivalTimeDateDiffUTC
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftArrivalTimeDateDiffUTC() {
    return aircraftArrivalTimeDateDiffUTC;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_U_T_C, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftArrivalTimeDateDiffUTC(@javax.annotation.Nullable Integer aircraftArrivalTimeDateDiffUTC) {
    this.aircraftArrivalTimeDateDiffUTC = aircraftArrivalTimeDateDiffUTC;
  }

  public Leg aircraftArrivalTimeLT(@javax.annotation.Nullable Integer aircraftArrivalTimeLT) {
    
    this.aircraftArrivalTimeLT = aircraftArrivalTimeLT;
    return this;
  }

  /**
   * The LT Aircraft Scheduled Time of Arrival for this leg in minutes
   * minimum: 1
   * maximum: 1440
   * @return aircraftArrivalTimeLT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftArrivalTimeLT() {
    return aircraftArrivalTimeLT;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftArrivalTimeLT(@javax.annotation.Nullable Integer aircraftArrivalTimeLT) {
    this.aircraftArrivalTimeLT = aircraftArrivalTimeLT;
  }

  public Leg aircraftArrivalTimeDateDiffLT(@javax.annotation.Nullable Integer aircraftArrivalTimeDateDiffLT) {
    
    this.aircraftArrivalTimeDateDiffLT = aircraftArrivalTimeDateDiffLT;
    return this;
  }

  /**
   * The date difference between the flight LT date and the aircraft arrival time of this leg in days.
   * minimum: -1
   * maximum: 10
   * @return aircraftArrivalTimeDateDiffLT
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftArrivalTimeDateDiffLT() {
    return aircraftArrivalTimeDateDiffLT;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_DATE_DIFF_L_T, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftArrivalTimeDateDiffLT(@javax.annotation.Nullable Integer aircraftArrivalTimeDateDiffLT) {
    this.aircraftArrivalTimeDateDiffLT = aircraftArrivalTimeDateDiffLT;
  }

  public Leg aircraftArrivalTimeVariation(@javax.annotation.Nullable Integer aircraftArrivalTimeVariation) {
    
    this.aircraftArrivalTimeVariation = aircraftArrivalTimeVariation;
    return this;
  }

  /**
   * The arrival time difference between the LT and UTC time in minutes.
   * @return aircraftArrivalTimeVariation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_VARIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAircraftArrivalTimeVariation() {
    return aircraftArrivalTimeVariation;
  }


  @JsonProperty(value = JSON_PROPERTY_AIRCRAFT_ARRIVAL_TIME_VARIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAircraftArrivalTimeVariation(@javax.annotation.Nullable Integer aircraftArrivalTimeVariation) {
    this.aircraftArrivalTimeVariation = aircraftArrivalTimeVariation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Leg leg = (Leg) o;
    return Objects.equals(this.sequenceNumber, leg.sequenceNumber) &&
        Objects.equals(this.origin, leg.origin) &&
        Objects.equals(this.destination, leg.destination) &&
        Objects.equals(this.serviceType, leg.serviceType) &&
        Objects.equals(this.aircraftOwner, leg.aircraftOwner) &&
        Objects.equals(this.aircraftType, leg.aircraftType) &&
        Objects.equals(this.aircraftConfigurationVersion, leg.aircraftConfigurationVersion) &&
        Objects.equals(this.registration, leg.registration) &&
        Objects.equals(this.op, leg.op) &&
        Objects.equals(this.aircraftDepartureTimeUTC, leg.aircraftDepartureTimeUTC) &&
        Objects.equals(this.aircraftDepartureTimeDateDiffUTC, leg.aircraftDepartureTimeDateDiffUTC) &&
        Objects.equals(this.aircraftDepartureTimeLT, leg.aircraftDepartureTimeLT) &&
        Objects.equals(this.aircraftDepartureTimeDateDiffLT, leg.aircraftDepartureTimeDateDiffLT) &&
        Objects.equals(this.aircraftDepartureTimeVariation, leg.aircraftDepartureTimeVariation) &&
        Objects.equals(this.aircraftArrivalTimeUTC, leg.aircraftArrivalTimeUTC) &&
        Objects.equals(this.aircraftArrivalTimeDateDiffUTC, leg.aircraftArrivalTimeDateDiffUTC) &&
        Objects.equals(this.aircraftArrivalTimeLT, leg.aircraftArrivalTimeLT) &&
        Objects.equals(this.aircraftArrivalTimeDateDiffLT, leg.aircraftArrivalTimeDateDiffLT) &&
        Objects.equals(this.aircraftArrivalTimeVariation, leg.aircraftArrivalTimeVariation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequenceNumber, origin, destination, serviceType, aircraftOwner, aircraftType, aircraftConfigurationVersion, registration, op, aircraftDepartureTimeUTC, aircraftDepartureTimeDateDiffUTC, aircraftDepartureTimeLT, aircraftDepartureTimeDateDiffLT, aircraftDepartureTimeVariation, aircraftArrivalTimeUTC, aircraftArrivalTimeDateDiffUTC, aircraftArrivalTimeLT, aircraftArrivalTimeDateDiffLT, aircraftArrivalTimeVariation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Leg {\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    aircraftOwner: ").append(toIndentedString(aircraftOwner)).append("\n");
    sb.append("    aircraftType: ").append(toIndentedString(aircraftType)).append("\n");
    sb.append("    aircraftConfigurationVersion: ").append(toIndentedString(aircraftConfigurationVersion)).append("\n");
    sb.append("    registration: ").append(toIndentedString(registration)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    aircraftDepartureTimeUTC: ").append(toIndentedString(aircraftDepartureTimeUTC)).append("\n");
    sb.append("    aircraftDepartureTimeDateDiffUTC: ").append(toIndentedString(aircraftDepartureTimeDateDiffUTC)).append("\n");
    sb.append("    aircraftDepartureTimeLT: ").append(toIndentedString(aircraftDepartureTimeLT)).append("\n");
    sb.append("    aircraftDepartureTimeDateDiffLT: ").append(toIndentedString(aircraftDepartureTimeDateDiffLT)).append("\n");
    sb.append("    aircraftDepartureTimeVariation: ").append(toIndentedString(aircraftDepartureTimeVariation)).append("\n");
    sb.append("    aircraftArrivalTimeUTC: ").append(toIndentedString(aircraftArrivalTimeUTC)).append("\n");
    sb.append("    aircraftArrivalTimeDateDiffUTC: ").append(toIndentedString(aircraftArrivalTimeDateDiffUTC)).append("\n");
    sb.append("    aircraftArrivalTimeLT: ").append(toIndentedString(aircraftArrivalTimeLT)).append("\n");
    sb.append("    aircraftArrivalTimeDateDiffLT: ").append(toIndentedString(aircraftArrivalTimeDateDiffLT)).append("\n");
    sb.append("    aircraftArrivalTimeVariation: ").append(toIndentedString(aircraftArrivalTimeVariation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

