/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.MessageLevel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Message
 */
@JsonPropertyOrder({
  Message.JSON_PROPERTY_TEXT,
  Message.JSON_PROPERTY_LEVEL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class Message {
  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_LEVEL = "level";
  @javax.annotation.Nullable
  private MessageLevel level;

  public Message() {
  }

  public Message text(@javax.annotation.Nullable String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Message text
   * @return text
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }

  public Message level(@javax.annotation.Nullable MessageLevel level) {
    
    this.level = level;
    return this;
  }

  /**
   * Get level
   * @return level
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MessageLevel getLevel() {
    return level;
  }


  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(@javax.annotation.Nullable MessageLevel level) {
    this.level = level;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.text, message.text) &&
        Objects.equals(this.level, message.level);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, level);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

