/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The combination of start date, end date and a weekday pattern
 */
@JsonPropertyOrder({
  PeriodOfOperation.JSON_PROPERTY_START_DATE,
  PeriodOfOperation.JSON_PROPERTY_END_DATE,
  PeriodOfOperation.JSON_PROPERTY_DAYS_OF_OPERATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class PeriodOfOperation {
  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @javax.annotation.Nonnull
  private String startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  @javax.annotation.Nonnull
  private String endDate;

  public static final String JSON_PROPERTY_DAYS_OF_OPERATION = "daysOfOperation";
  @javax.annotation.Nonnull
  private String daysOfOperation;

  public PeriodOfOperation() {
  }

  public PeriodOfOperation startDate(@javax.annotation.Nonnull String startDate) {
    
    this.startDate = startDate;
    return this;
  }

  /**
   * The start date of this period in the format &#39;DDMMMYY&#39;
   * @return startDate
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartDate() {
    return startDate;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartDate(@javax.annotation.Nonnull String startDate) {
    this.startDate = startDate;
  }

  public PeriodOfOperation endDate(@javax.annotation.Nonnull String endDate) {
    
    this.endDate = endDate;
    return this;
  }

  /**
   * The start date of this period in the format &#39;DDMMMYY&#39;
   * @return endDate
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEndDate() {
    return endDate;
  }


  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndDate(@javax.annotation.Nonnull String endDate) {
    this.endDate = endDate;
  }

  public PeriodOfOperation daysOfOperation(@javax.annotation.Nonnull String daysOfOperation) {
    
    this.daysOfOperation = daysOfOperation;
    return this;
  }

  /**
   * String representation of the days of operation (weekdays) in the format &#39;fffffff&#39; with whitespace padding
   * @return daysOfOperation
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DAYS_OF_OPERATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDaysOfOperation() {
    return daysOfOperation;
  }


  @JsonProperty(value = JSON_PROPERTY_DAYS_OF_OPERATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDaysOfOperation(@javax.annotation.Nonnull String daysOfOperation) {
    this.daysOfOperation = daysOfOperation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeriodOfOperation periodOfOperation = (PeriodOfOperation) o;
    return Objects.equals(this.startDate, periodOfOperation.startDate) &&
        Objects.equals(this.endDate, periodOfOperation.endDate) &&
        Objects.equals(this.daysOfOperation, periodOfOperation.daysOfOperation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, endDate, daysOfOperation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeriodOfOperation {\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    daysOfOperation: ").append(toIndentedString(daysOfOperation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

