/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The intended time mode. Either Universal Time Coordinated (UTC) or Local Time (LT)
 */
public enum TimeMode {
  
  UTC("UTC"),
  
  LT("LT");

  private String value;

  TimeMode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TimeMode fromValue(String value) {
    for (TimeMode b : TimeMode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

