openapi: 3.0.0
info:
  title: Planes.cards
  description: Planes.cards
  version: 1.0.0
servers:
  - url: 'https://api.planes.cards/'
paths:
  /health:
    get:
      operationId: health
      tags:
        - health
      responses:
        200:
          description: "Health check"
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: string
                    example: "ok"

  /party/join:
    get:
      operationId: joinGame
      tags:
        - pre-game
      responses:
        200:
          description: "Join party"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartyJoin"

  /party/{partyId}:
    get:
      operationId: getPartyUpdates
      tags:
        - running-game
      summary: "Get Game Updates via websocket"
      parameters:
        - in: path
          name: partyId
          schema:
            type: string
          required: true
          description: "provided party id"
      responses:
        200:
          description: "Game Updates via websocket"

  /party/{partyId}/update:
    post:
      operationId: sendPartyUpdates
      tags:
        - running-game
      summary: "Client updates party"
      parameters:
        - in: path
          name: partyId
          schema:
            type: string
          required: true
          description: "provided party id"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PartyClientUpdate"
      responses:
        200:
          description: "Accepted"

components:
  schemas:
    PartyJoin:
      type: object
      required:
        - yourId
        - partyId
      properties:
        yourId:
          type: string
          example: "UUI"
        partyId:
          type: string
          example: "UUI"

    PartyGame:
      type: object
      required:
        - partyId
        - state
        - players
      properties:
        partyId:
          type: string
          example: "UUID"
        state:
          $ref: "#/components/schemas/GameState"
        players:
          type: array
          items:
            $ref: "#/components/schemas/GamePlayer"
        lastRoundWinner:
          type: string
          description: "ID of player who won the last round"

    GamePlayer:
      type: object
      required:
        - id
        - cards
        - score
        - yourTurn
      properties:
        id:
          type: string
          example: "id"
        yourTurn:
          type: boolean
          example: true
        playedCard:
          $ref: "#/components/schemas/GameCard"
        cards:
          type: array
          items:
            $ref: "#/components/schemas/GameCard"
        score:
          type: integer
          example: 0
          description: "Player's current score"

    GameCard:
      type: object
      required:
        - flightNumber
        - startAirport
        - destinationAirport
        - boardingTime
        - estimatedLanding
        - seatNumber
        - id
        - travelDistance
        - flightTime
      properties:
        id:
          type: string
        aircraft:
          type: string
          example: "BOEING 747 MEGA LARGE"
        seatNumber:
          type: string
          example: "12"
        flightNumber:
          type: string
          example: "HAHALOSER"
        startAirport:
          type: string
          example: "HAMBURG"
        boardingTime:
          type: string
          format: date-time
          example: "2026-01-01T12:00:00"
        estimatedLanding:
          type: string
          format: date-time
          example: "2026-01-02T12:00:00"
        destinationAirport:
          type: string
          example: "WASHINGTION DC"
        flightTime:
          type: number
          description: "IN Minutes"
          example: "1200000"
        travelDistance:
          type: number
          description: "Distance in meter"


    GameState:
      enum:
        - WAITING
        #- SELECT_AIRPORT
        - WAITING_FOR_CARDS
        - ENDING

    PartyClientUpdate:
      type: object
      required:
        - yourId
      properties:
        yourId:
          type: string
          example: "UUID"
        playCard:
          $ref: "#/components/schemas/PartyClientPlayedCard"

    PartyClientPlayedCard:
      type: object
      required:
        - attribute
        - playedCard
      properties:
        attribute:
          type: string
          example: "flightNumber"
        playedCard:
          $ref: "#/components/schemas/GameCard"

