/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.FlightAggregate;
import org.openapitools.client.model.TimeMode;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ScheduleApi
 */
@Disabled
public class ScheduleApiTest {

    private final ScheduleApi api = new ScheduleApi();

    
    /**
     * Returns cargo flights
     *
     * This operation returns schedules related to cargo flights only. In case a flight is marked both as cargo and passenger it will also be returned.
     */
    @Test
    public void flightschedulesCargoGetTest()  {
        // uncomment below to test the function
        //List<String> airlines = null;
        //String startDate = null;
        //String endDate = null;
        //String daysOfOperation = null;
        //TimeMode timeMode = null;
        //String flightNumberRanges = null;
        //String origin = null;
        //String destination = null;
        //List<String> aircraftTypes = null;
        //List<FlightAggregate> response = api.flightschedulesCargoGet(airlines, startDate, endDate, daysOfOperation, timeMode, flightNumberRanges, origin, destination, aircraftTypes).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Search all flights
     *
     * Returns information about all flights based on available search criteria. Some criteria are mandatory to make a call to the API.
     */
    @Test
    public void flightschedulesGetTest()  {
        // uncomment below to test the function
        //List<String> airlines = null;
        //String startDate = null;
        //String endDate = null;
        //String daysOfOperation = null;
        //TimeMode timeMode = null;
        //String flightNumberRanges = null;
        //String origin = null;
        //String destination = null;
        //List<String> aircraftTypes = null;
        //List<FlightAggregate> response = api.flightschedulesGet(airlines, startDate, endDate, daysOfOperation, timeMode, flightNumberRanges, origin, destination, aircraftTypes).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Returns passenger flights
     *
     * This operation returns schedules related only to passenger flights. In case a flight is marked both as cargo and passenger it will also be returned.
     */
    @Test
    public void flightschedulesPassengerGetTest()  {
        // uncomment below to test the function
        //List<String> airlines = null;
        //String startDate = null;
        //String endDate = null;
        //String daysOfOperation = null;
        //TimeMode timeMode = null;
        //String flightNumberRanges = null;
        //String origin = null;
        //String destination = null;
        //List<String> aircraftTypes = null;
        //List<FlightAggregate> response = api.flightschedulesPassengerGet(airlines, startDate, endDate, daysOfOperation, timeMode, flightNumberRanges, origin, destination, aircraftTypes).collectList().block();

        // TODO: test validations
    }
    
}
