/*
 * Flight Schedules API
 * This API provides Lufthansa's flight schedule information.  A search functionality is available based on a number of criteria:   * airlines   * flight number   * start and end date   * days of operation   * origin and destination   * aircraft types    Depending on access it enables to view passenger flights, cargo flights or both.  The flights returned are date-wise aggregated.  Their structure and attributes follow the standards and definitions provided by the IATA Standard Schedules Information Manual (SSIM, Chapter 2). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api.support@lufthansa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.auth;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

import org.springframework.http.HttpHeaders;
import org.springframework.util.MultiValueMap;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-28T13:12:20.084199429+01:00[Europe/Berlin]", comments = "Generator version: 7.20.0")
public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToParams(MultiValueMap<String, String> queryParams, HttpHeaders headerParams, MultiValueMap<String, String> cookieParams) {
        if (username == null && password == null) {
            return;
        }
        String str = (username == null ? "" : username) + ":" + (password == null ? "" : password);
        headerParams.add(HttpHeaders.AUTHORIZATION, "Basic " + Base64.getEncoder().encodeToString(str.getBytes(StandardCharsets.UTF_8)));
    }
}
